# Generated by Django 5.1.5 on 2025-02-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('click_count', models.IntegerField(default=0)),
                ('author', models.CharField(default='null', max_length=150)),
            ],
        ),
    ]
