# Generated by Django 5.1.5 on 2025-02-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortener', '0002_shorturl_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='author',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
